name: 'Semantic Linter'
description: 'Lints pull requests using an LLM to enforce semantic rules.'
author: 'Roo'

inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret.'
    required: true
  config-path:
    description: 'Path to the linter configuration file.'
    required: true
    default: '.github/linter.yml'
  llm-provider:
    description: 'The LLM provider to use (e.g., openai, anthropic).'
    required: true
    default: 'openai'
  llm-api-key:
    description: 'The API key for the selected LLM provider.'
    required: true
  llm-model:
    description: 'The specific model to use (e.g., gpt-4, gemini-pro).'
    required: false
  max-retries:
    description: 'The maximum number of retries for failed API calls.'
    required: false
    default: '3'
  retry-delay:
    description: 'The delay in milliseconds between retries.'
    required: false
    default: '1000'

runs:
  using: 'node20'
  main: 'dist/index.js'